### ISSUE TITLE
Should we allow long blocks in CatalogController?

### ISSUE THREAD

**Issue by no-reply** [samvera-labs/bixby#3]
Starting a new Hyrax project on bixby, I found I needed to introduce only two exceptions to the style guide here to get to green CI (after `rubocop:auto_correct). Both are related to the length of `CatalogController` and its internal blocks. 

The proposed rule would be something like:

```yaml
Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - '**/*/catalog_controller.rb'

Metrics/ClassLength:
  Exclude:
    - '**/*/catalog_controller.rb'
```
See: https://github.com/curationexperts/epigaea/pull/53/commits/d76c5f1899c269cbac86fd36e759fe180cfff18a#diff-11a0d7906801d9dea0eccb85667ad811R4
